### ISSUE TITLE
Problems with manage command

### ISSUE THREAD

**Issue by silentworks** [garethr/django-project-templates#1]
When I try and run manage startapp command on the newsapp_project it creates the app in the common directory and not the app directory, could you add some sort of instruction how to setup this up properly as their seem to be little to none on this.

**Comment by dreamiurg** [comment]
See the following code in src/django_project_templates/templates/newsapps_project/+project+/configs/common/manage.py :

```
# we have have a local apps directory
apps_path = os.path.join(
    os.path.realpath(os.path.dirname(__file__)), '../../apps'
)
```

The `app_path` variable specifies root folder for your applications. Modify it to your flavors.

**Comment by silentworks** [comment]
unfortunately that doesn't help when it comes on to startapp command, it works with runserver command. I got a reply on how to use startapp in the comments of this block post.

http://blog.apps.chicagotribune.com/2010/03/08/advanced-django-project-layout/

**Comment by dreamiurg** [comment]
That makes sense. Should this issue be closed then?
